### PR TITLE
Added re-formatted index.html

### PR DESCRIPTION
**Pull request by Pinacolada64**
May make adding commands easier by virtue of HTML tags being on separate lines -- less horizontal cursor movement.

### CODE REVIEW

**Comment by Pinacolada64** [comment]
Sorry if I stepped on any toes with the table HTML. I'll fix it.

**Comment by Pinacolada64** [comment]
Argh. Didn't mean to do that.

**Comment by AmberFennek** [comment]
Press all the buttons!
Thank you for the help.
Also, keep practicing your git-fu.

**Comment by Pinacolada64** [comment]
I like pressing buttons!
You are welcome, @AmberFennek.
I shall try.

**Pull request merged**
